
// try/catch: define um bloco para tratar o erro

let a = 50;
let b = 30;

// Tente executar o código
try {
    console.log(a+d)

// captura o erro
}catch(error){
    console.log(error)

// imprime independente do resultado
}finally{
    console.log("Final da execução")
}